//STEP 1 USE WINGET TOOL TO INSTALL AZURE CLI
 winget install --exact --id Microsoft.AzureCLI


 // STEP 2 CHECK THAT AZURE CLI INSTALLED
 az --version

// STEP3 LOGIN USING MULTIFACTOR AUTHENTICATION
 az login --use-device-code

// STEP 4 GO THE WEBSITE URL AND PASTE THE LOGIN CODE
https://login.microsoft.com/device
C3KP9SFFB

// STEP 5 PRESS ENTER WHEN AZURE ASKS YOU FOR SUBSCRIPTION