spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8081